Implement GPhase init_super
wagrenier/Mikompilation pull request #15
Opened 2022-06-01 02:04 UTC by kenshen112

Implements GPhase init_super

2022-06-01 11:11 UTC, wagrenier requested changes

2022-06-01 11:11 UTC, wagrenier commented on engine/gra3d/draw_env.h
> +void InitDrawEnv(int, void*, int, void*, void*, int**, void*, int**);
incomplete parameter definitions

2022-06-01 11:11 UTC, wagrenier commented on engine/gra3d/gra3d.cpp
> +
remove extra new lines

2022-06-01 11:11 UTC, wagrenier commented on engine/gra3d/gra3d.cpp
> +
add not implemented

2022-06-01 11:11 UTC, wagrenier commented on engine/gra3d/gra3d.h
> +
`#pragma once`

2022-06-01 11:11 UTC, wagrenier commented on engine/message.cpp
> +
remove extra new lines

2022-06-01 11:11 UTC, wagrenier commented on engine/message.cpp
> +
Add not implemented

2022-06-01 11:11 UTC, wagrenier commented on game/MemoryCard/mc.cpp
> +
remove extra new lines

2022-06-01 11:11 UTC, wagrenier commented on game/MemoryCard/mc.cpp
> +  memoryCard = new uint32_t[MB(8)];
We are not implementing a memory card

2022-06-01 11:11 UTC, wagrenier commented on game/finder/finder.cpp
> +	// SndBankNew(0xc8a,0xc89,0xffffffffffffffff);
remove extra new lines

Add not implemented

2022-06-01 11:11 UTC, wagrenier commented on game/ingame.cpp
> +
remove extra new lines

2022-06-01 11:11 UTC, wagrenier commented on game/ingame.cpp
> +
add not implemented

2022-06-01 11:11 UTC, wagrenier commented on game/ingame.cpp
> +void IngameWrkInit(int, int)
incomplete method definition, this shouldnt even compile

2022-06-01 11:11 UTC, wagrenier commented on game/menu/logo_main.h
> +
remove extra new lines

2022-06-01 11:11 UTC, wagrenier commented on game/menu/title_menu.cpp
> +  title_bg_addr = NULL;
`nullptr`

2022-06-01 11:11 UTC, wagrenier commented on game/menu/title_menu.cpp
> +  title_bg_send_lock = NULL;
`nullptr`

2022-06-01 11:11 UTC, wagrenier commented on game/menu/title_menu.cpp
> +  title_load_end = NULL;
`nullptr`

2022-06-01 11:11 UTC, wagrenier commented on game/scene/scene.h
> +struct SCENE_CTRL {
newline bracket

2022-06-01 11:11 UTC, wagrenier commented on game/scene/scene_effect.h
> +enum Effects
define your enum as an int enum by doing: `enum : int`

2022-06-01 11:11 UTC, wagrenier commented on engine/g2d/g2d_main.cpp
> +
remove extraa newline

2022-06-01 11:11 UTC, wagrenier commented on game/ingame.h
> +void IngameWrkInit(int, int);
Incomplete method definition

2022-06-01 11:11 UTC, wagrenier commented on game/system/system.cpp
> +  // cddatInit(param 1, param 2, param 3);
The function taakes more parameters thant that

2022-06-01 11:17 UTC, wagrenier commented
Additional change request, in the clang-formaat file can you add: `AfterStruct:     true` under the `BraceWrapping`

2022-06-01 15:40 UTC, kenshen112 commented on engine/fade.h
> +#include <iostream>
It adds memest or malloc to the cop file

2022-06-01 15:43 UTC, wagrenier commented on engine/fade.h
> +#include <iostream>
Yes but that isnt used in the .h file so it would be better to import in the `.cpp` file, since only the code part needs it

2022-06-01 15:49 UTC, wagrenier commented on engine/fade.cpp
> +  void *varMem = memset(&fade_ctrl, 0, 0xc);
Also, it would be better to do sizeof(FADE_CTRL) for the last argument, if we know that it is the size of `fade_ctrl`

2022-06-02 01:03 UTC, kenshen112 commented on engine/fade.cpp
> +  void *varMem = memset(&fade_ctrl, 0, 0xc);
That's more accurate to the logic in the original game they use a memset to write 0 to clear a struct. They're not allocating a pointer

2022-06-02 01:40 UTC, wagrenier requested changes

2022-06-02 01:40 UTC, wagrenier commented on engine/fade.cpp
> +  void *varMem = memset(&fade_ctrl, 0, 0xc);
Your `memset` is writing over memory that does not belong to the struct. Make sure the struct is the right size and use the `sizeof` like the original code did

2022-06-02 01:40 UTC, wagrenier commented on game/system/option.h
> +void InitOptionSetup(OPTION_WRK * options);
put the `*` next to the parameter name

2022-06-02 02:13 UTC, wagrenier approved these changes

2022-06-02 02:16 UTC, merged